FROM ubuntu:22.04

RUN apt update && \
    apt install -yq cmake build-essential ninja-build \
    libcrypto++-dev libfmt-dev liblua5.4-dev libluajit-5.1-dev libmysqlclient-dev \
    libboost-iostreams-dev libboost-locale-dev libboost-system-dev libpugixml-dev

ARG BUILD_TYPE="RelWithDebInfo"
ARG USE_LUAJIT="ON"
ARG ENABLE_UNITY_BUILD="ON"
ARG ENABLE_OTS_STATISTICS="ON"

COPY cmake /usr/src/forgottenserver/cmake/
COPY src /usr/src/forgottenserver/src/
COPY CMakeLists.txt CMakePresets.json /usr/src/forgottenserver/
WORKDIR /usr/src/forgottenserver

RUN cmake --preset default \
    -DUSE_LUAJIT=${USE_LUAJIT} \
    -DENABLE_UNITY_BUILD=${ENABLE_UNITY_BUILD} \
    -DENABLE_OTS_STATISTICS=${ENABLE_OTS_STATISTICS} \
    && cmake --build --config ${BUILD_TYPE} --preset default
